# Single vcard
vcard:
    path: /{person}
    defaults: { _controller: CorporateVCardsBundle:VCard:vCard }

# Download .vcf file
vcard_download:
    path: /{person}/download
    defaults: { _controller: CorporateVCardsBundle:VCard:downloadVcard }

# Download .vcf file from its information
vcard_download_frominfos:
    path: /{person}/download_vcard
    defaults: { _controller: CorporateVCardsBundle:VCard:downloadVcardFromInfos }

# Return a QR Code containing person's vcard
vcard_qrCode:
    path: /{person}/qrCode
    defaults: { _controller: CorporateVCardsBundle:VCard:qrCode }
