services:
    corporate_v_cards.vcard:
        class: AtlanteGroup\CorporateVCardsBundle\Service\VCardService
        arguments:
            profiles: '%corporate_v_cards.profiles%'
            defaultProfile: '%corporate_v_cards.default%'
            kernelRootDir: "%kernel.root_dir%"
            requestStack: "@request_stack"

    app.twig_extension:
        class: AtlanteGroup\CorporateVCardsBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
